//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpRestaurant.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CpRestaurant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap account_circle_100dp_000000_FILL0_wght700_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("account_circle_100dp_000000_FILL0_wght700_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_circle_40dp_000000_FILL1_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("add_circle_40dp_000000_FILL1_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_40dp_000000_FILL1_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("cancel_40dp_000000_FILL1_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_50dp_000000_FILL0_wght500_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("close_50dp_000000_FILL0_wght500_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_50dp_000000_FILL0_wght500_GRAD0_opsz481 {
            get {
                object obj = ResourceManager.GetObject("close_50dp_000000_FILL0_wght500_GRAD0_opsz481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_40dp_000000_FILL1_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("delete_40dp_000000_FILL1_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dining_50dp_000000_FILL1_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("dining_50dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_40dp_000000_FILL1_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("edit_40dp_000000_FILL1_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iniciar_sesion {
            get {
                object obj = ResourceManager.GetObject("iniciar-sesion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_50dp_000000_FILL0_wght500_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("login_50dp_000000_FILL0_wght500_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nutrition_40dp_000000_FILL1_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("nutrition_40dp_000000_FILL1_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_50dp_000000_FILL1_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("person_50dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plana_laicos_pollo_al_horno_y_rodajas_de_naranja_en_un_plato_con_cubiertos_y_bloc_de_notas_en_blanco {
            get {
                object obj = ResourceManager.GetObject("plana-laicos-pollo-al-horno-y-rodajas-de-naranja-en-un-plato-con-cubiertos-y-bloc" +
                        "-de-notas-en-blanco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap point_of_sale_40dp_000000_FILL1_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("point_of_sale_40dp_000000_FILL1_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_40dp_000000_FILL1_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("save_40dp_000000_FILL1_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_40dp_000000_FILL1_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("search_40dp_000000_FILL1_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
