//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id { get; set; }
        public int idPlatillo { get; set; }
        public int idCliente { get; set; }
        public decimal precioUnitario { get; set; }
        public int cantidad { get; set; }
        public decimal total { get; set; }
        public decimal efectivo { get; set; }
        public decimal cambio { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Platillo Platillo { get; set; }
    }
}
